# Generated by Django 5.2.13 on 2026-09-16 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('moradia', 'Moradia'), ('lazer', 'Lazer'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('compras', 'Compras'), ('outros', 'Outros')], max_length=20)),
                ('installment_number', models.PositiveIntegerField(blank=True, null=True)),
                ('total_installments', models.PositiveIntegerField(blank=True, null=True)),
                ('installment_group', models.UUIDField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
